name: PipelineWorkflow

on:
  push:
    brunches:
      - master
  pull_request:
    brunches:
      - master

jobs:
  build:
    name: Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipeline Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/ayan9093/AgileProject
          azure-pipeline-name: 'devops-shuddha18.gitapp'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
